version: '3.9'
services:
    pg:
        image: postgres:latest
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - target: 5432
              published: 5432